export {
  addressJson,
  addressesFromRecipientJson,
  assertDocxInflatesWithinLimit,
  ATTACHMENT_TEXT_EXTRACTOR_VERSION,
  ATTACHMENT_TEXT_MAX_BYTES,
  ATTACHMENT_TEXT_MAX_CHARS,
  attachmentTextKind,
  capAttachmentText,
  decodeAttachmentText,
  refineAttachmentTextKind,
  CID_INLINE_MIN_BUDGET_BYTES,
  cidInlineBudgetBytes,
  decodeHtmlEntities,
  formatDate,
  formatMailparserHeaderValue,
  inlineCidImages,
  isCorruptRawHeaders,
  normalizeAddressJson,
  parseAttachmentsMeta,
  plainTextFromHtml,
  rawHeadersFromParsed,
  snippetFromParsed,
  type AttachmentTextKind,
  type CanonicalAddressJson,
  type DocxZipLoader,
} from '../../packages/core/src/email';
