export const SETTINGS_TAB_IDS = [
  "accounts",
  "oauthApps",
  "ai",
  "knowledge",
  "mailSecurity",
  "tracking",
  "smtpRelay",
  "delegation",
  "automation",
  "prompts",
  "team",
  "appUsers",
  "authSecurity",
  "userGroups",
  "canned",
  "export",
  "pgp",
  "auditLog",
  "threadTools",
  "snooze",
  "diagnostics",
  "misc",
] as const
